### ISSUE TITLE
Not possible to use a list of strings in configuration

### ISSUE THREAD

**Issue by slawor** [PHOENIXCONTACT/MORYX-MaintenanceWeb#25] opened 2020-11-04 08:28 UTC
If i want to use a configuration property like

![image](https://user-images.githubusercontent.com/16089808/98086041-7a35f080-1e7e-11eb-85ed-48491d24ab6b.png)

then i have the following problem and it is not possible to configure the mentioned list.
The first two entries are expanded in the picture.

![image](https://user-images.githubusercontent.com/16089808/98086210-b9fcd800-1e7e-11eb-86b2-5e94ad0aff91.png)

I expected just to chnage or add some strings.

**Comment by dbeuchler** [comment] 2020-11-05 16:49
Within the EntryEditor of the client framework it works 
![image](https://user-images.githubusercontent.com/920832/98270573-4b5b6f80-1f8f-11eb-8fb0-c378bc6ab6a7.png)

**Comment by dbeuchler** [comment] 2020-11-05 16:56
@Toxantron I have seen another thing which might came up if this will be fixed in the maintenance web. If I add another string entry to the list a dropdown will be provided. This happens because the prototype of the collection contains `PossibleValues`:

````cs
dataTemplate = configEntryModel.PossibleValues == null ? StringTemplate : DropDownTemplate;
````

![image](https://user-images.githubusercontent.com/920832/98271343-26b3c780-1f90-11eb-8c3e-bd74b243fc36.png)

**Comment by Toxantron** [comment] 2020-11-05 18:29
I guess the problem is on the server side, probably somewhere around `PossibleValuesSerialization`.

**Comment by mmarkwort** [comment] 2020-11-08 18:36
Do you really want to apply a complete list or do you want to have a drop down with predefined values?

If so, you need you can use `PrimitiveValues`:
```cs
[PrimitiveValues("Name1", "Hello", "Name2", "Name3")]
```

Then a drop down is shown:

![image](https://user-images.githubusercontent.com/26304706/98481198-f0c54c00-21f8-11eb-9357-dfb3bad31a0c.png)

**Comment by mmarkwort** [comment] 2020-11-08 21:58
@Toxantron 
This bug has two bugs:
1) Missing support for list of primitives -> see PR
2) I agree with you. There is a bug in `PossibleValuesSerialization`: In case of a list or primitives there should no possible value by default.

**Comment by Toxantron** [comment] 2020-11-09 05:38
@mmarkwort I took care of the platform in PHOENIXCONTACT/MORYX-Platform#76.

**Comment by slawor** [comment] 2020-11-09 09:28
> @slawor
> Do you really want to apply a complete list or do you want to have a drop down with predefined values?
> 
> If so, you need you can use `PrimitiveValues`:
> 
> ```cs
> [PrimitiveValues("Name1", "Hello", "Name2", "Name3")]
> ```
> 
> Then a drop down is shown:
> 
> ![image](https://user-images.githubusercontent.com/26304706/98481198-f0c54c00-21f8-11eb-9357-dfb3bad31a0c.png)

In my case i want to apply a list of strings without predefined values

**Closed** 2020-11-10 10:34 UTC
Labels: bug
